# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APISampleUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APISampleUI
  pod 'Alamofire', '~> 5.5'
  pod 'ObjectMapper', '~> 3.5'

  target 'APISampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APISampleUIUITests' do
    # Pods for testing
  end

end
